[build]
  command = "npm run build"
  publish = "./"

  [build.environment]
    NODE_VERSION = "18"

# serve blog.html as the homepage
[[redirects]]
  from = "/"
  to = "/blog.html"
  status = 200

# redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
