services:
  - type: web
    name: myblog
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLISH_PASSWORD
        fromSecret: PUBLISH_PASSWORD
